tasks/config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  get "/auth/:provider/callback", to: "sessions#create"

  resource :sessions

  resources :tasks do
    collection do
      post :assign_all
    end

    member do
      post :done
    end
  end
end

tasks/app/models/account.rb
class Account < ActiveRecord::Base
  extend Enumerize

  enumerize :role, in: [:admin, :manager, :employee], predicates: true, scope: :shallow
end

tasks/app/models/task.rb
class Task < ApplicationRecord
  extend Enumerize

  enumerize :status, in: [:created, :done], predicates: true, scope: :shallow

  validate :name_doesnt_contain_jira?

  def name_doesnt_contain_jira?
    self.name.blank? || self.name.exclude?('[')
  end
end

tasks/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy done ]

  # GET /tasks or /tasks.json
  def index
    @tasks = []

    if current_account.employee?
      @tasks = Task.where(assignee_id: current_account.id)
    elsif current_account.admin? || current_account.manager?
      @tasks = Task.all
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.created_by_id = current_account.id
    @task.status = :created

    respond_to do |format|
      if @task.save
        event = {
          event_name: 'TaskCreated',
          id: SecureRandom.uuid,
          version: '2',
          created_at: Time.now.to_s,
          producer: 'tasks',
          data: {
            public_id: @task.public_id,
            assignee_id: @task.assignee.public_id,
            created_by_id: current_account.public_id,
            jira_id: @task.jira_id
          }
        }
        result = SchemaRegistry.validate_event(event, 'tasks.created', version: 2)
        if result.success?
          WaterDrop::SyncProducer.call(event.to_json, topic: 'tasks-stream')
        else
          raise result.failure
        end

        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)

        updated_event = {
          event_name: 'TaskUpdated',
          id: SecureRandom.uuid,
          version: '2',
          created_at: Time.now.to_s,
          producer: 'tasks',
          data: {
            public_id: @task.public_id,
            assignee_id: @task.assignee.public_id,
            status: @task.status,
            jira_id: @task.jira_id
          }
        }
        result = SchemaRegistry.validate_event(event, 'tasks.updated', version: 2)
        if result.success?
          WaterDrop::SyncProducer.call(updated_event.to_json, topic: 'tasks-stream')
        else
          raise result.failure
        end

        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def assign_all
    Task.transaction do
      assignable_ids = Account.employee.pluck(:public_id)
      Task.created.each { |t| random_assign(assignable_ids, t) }
    end
  end

  def done
    @task.update(status: :done)

    event = {
      event_name: 'TaskCompleted',
      id: SecureRandom.uuid,
      version: '1',
      created_at: Time.now.to_s,
      producer: 'tasks',
      data: {
        public_id: @task.public_id,
      }
    }
    result = SchemaRegistry.validate_event(event, 'tasks.completed', version: 1)
    if result.success?
      WaterDrop::SyncProducer.call(event.to_json, topic: 'tasks')
    else
      raise result.failure
    end

    updated_event = {
      event_name: 'TaskUpdated',
      id: SecureRandom.uuid,
      version: '1',
      created_at: Time.now.to_s,
      producer: 'tasks',
      data: {
        public_id: @task.public_id,
        status: @task.status,
      }
    }
    result = SchemaRegistry.validate_event(event, 'tasks.updated', version: 1)
    if result.success?
      WaterDrop::SyncProducer.call(updated_event.to_json, topic: 'tasks-stream')
    else
      raise result.failure
    end

  end

  private

  def random_assign(assignable_ids, task)
    assignee_id = assignable_ids.sample
    task.update(assignee: assignee_id)

    assign_data = { public_id: @task.public_id, assignee_id: assignee_id }

    assigned_event = {
      event_name: 'TaskAssigned',
      id: SecureRandom.uuid,
      version: '1',
      created_at: Time.now.to_s,
      producer: 'tasks',
      data: assign_data }
    result = SchemaRegistry.validate_event(event, 'tasks.assigned', version: 1)
    if result.success?
      WaterDrop::SyncProducer.call(assigned_event.to_json, topic: 'tasks')
    else
      raise result.failure
    end

    updated_event = {
      event_name: 'TaskUpdated',
      id: SecureRandom.uuid,
      version: '1',
      created_at: Time.now.to_s,
      producer: 'tasks',
      data: assign_data }
    result = SchemaRegistry.validate_event(event, 'tasks.updated', version: 1)
    if result.success?
      WaterDrop::SyncProducer.call(updated_event.to_json, topic: 'tasks-stream')
    else
      raise result.failure
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :created_by_id, :assignee_id, :status, :assign_amount, :complete_amount, :jira_id)
  end
end

tasks/app/helpers/accounts_helper.rb
module AccountsHelper
end

tasks/app/helpers/tasks_helper.rb
module TasksHelper
end

tasks/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

tasks/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :jira_id %>
    <%= form.text_field :jira_id %>
  </div>

  <div class="field">
    <%= form.label :created_by_id %>
    <%= form.text_field :created_by_id %>
  </div>

  <div class="field">
    <%= form.label :assignee_id %>
    <%= form.text_field :assignee_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :assign_amount %>
    <%= form.text_field :assign_amount %>
  </div>

  <div class="field">
    <%= form.label :complete_amount %>
    <%= form.text_field :complete_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

tasks/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Jira id</th>
      <th>Created by</th>
      <th>Assignee</th>
      <th>Status</th>
      <th>Assign amount</th>
      <th>Complete amount</th>
      <th colspan=<%= 3 + (current_account.employee? ? 1 : 0) %>></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.jira_id %></td>
        <td><%= task.created_by_id %></td>
        <td><%= task.assignee_id %></td>
        <td><%= task.status %></td>
        <td><%= task.assign_amount %></td>
        <td><%= task.complete_amount %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if current_account.employee? %>
          <td><%= link_to 'Done', done_task_path(task), method: :post %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

<% if current_account.admin? || current_account.manager? %>
  <%= link_to 'Assign tasks', assign_all_tasks_path, method: :post %>
<% end %>

tasks/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with(model: @task) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :jira_id %>
    <%= form.text_field :jira_id %>
  </div>

  <div class="field">
    <%= form.label :assignee_id %>
    <%= form.text_field :assignee_id %>
  </div>

  <div class="field">
    <%= form.label :assign_amount %>
    <%= form.text_field :assign_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', tasks_path %>

tasks/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Jira id:</strong>
  <%= @task.jira_id %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @task.created_by_id %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @task.assignee_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Assign amount:</strong>
  <%= @task.assign_amount %>
</p>

<p>
  <strong>Complete amount:</strong>
  <%= @task.complete_amount %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>